services:
  mysql:
    image: mysql:latest
    env_file: ./env/mysql.env
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: gabrielbrazdev89/arquitetura-java:latest
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
